spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.189:3306/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: F:/var/log/tomcat/
#  file: F:/var/log/tomcat/sell.log
#  level:
#    com.plm.LoggerTest: debug